### ISSUE TITLE
Regression in error message when no browser is found

### ISSUE THREAD

**Issue by jeswr** [extension-js/extension.js#138]
Regression in error message when browser is not found.

Before upgrading the error the message is: "chrome-browser  ✖︎✖︎✖︎ Chrome browser is not found at null. Either install Chrome or choose a different browser via --browser."
 
 After  upgrading it becomes: "TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received null".
 
 Full errors are in the following logs.

```bash
$ npm run dev

> who-do-i-trust-extension@0.0.0 dev
> extension dev


Your 🧩 Extension version is outdated.
The latest version is 1.8.0. Please update!

 chrome-browser  ✖︎✖︎✖︎ Chrome browser is not found at null. Either install Chrome or choose a different browser via --browser.
$ npm upgrade
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated webextension-polyfill-ts@0.26.0: This project has moved to @types/webextension-polyfill

added 83 packages, removed 64 packages, changed 224 packages, and audited 898 packages in 3m

180 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ npm run dev

> who-do-i-trust-extension@0.0.0 dev
> extension dev

node:internal/errors:540
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received null
    at Object.resolve (node:path:1128:7)
    at y.launchChrome (/home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/webpack-run-chrome-extension/dist/module.js:14:10581)
    at /home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/webpack-run-chrome-extension/dist/module.js:14:11552
    at Hook.eval [as callAsync] (eval at create (/home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/tapable/lib/Hook.js:18:14)
    at /home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/webpack/lib/Compiler.js:1007:27
    at /home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/neo-async/async.js:2818:7
    at done (/home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/neo-async/async.js:3522:9)
    at eval (eval at create (/home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/webpack-dev-middleware/dist/utils/setupWriteToDisk.js:56:20
    at /home/jeswr/Documents/Github/jeswr/who-do-i-trust-extension/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:187:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v22.5.1
$ node --version
v22.5.1
$ npm --version
10.8.2
```

**Comment by cezaraugusto** [comment]
hi @jeswr, thanks for reporting! This will be patched in the next release which should happen in the next few days.

**Comment by cezaraugusto** [comment]
Hi @jeswr sorry for the long delay. Extension.js is now at v2.0.0 (still alpha) and your issue seems fixed. Could you please re-check?

**Comment by jeswr** [comment]
Hi, thanks for addressing this!

I'm not currently working with extensions and won't have time to test this soon; but assuming the linked issue is solved, I think it is safe to assume this one is also solved

**Comment by cezaraugusto** [comment]
Thanks!
